### ISSUE TITLE
Invalid variable names 

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OMSimulator-testsuite#49]
@robbr48 Variable names cannot contain unit information.

https://github.com/OpenModelica/OMSimulator-testsuite/blob/9f330bbc1d35b81acd7abfd727ea63165f5e8351/OMTLMSimulator/TLM_FMI_1D_CoarseGrained.lua#L49

**Comment by robbr48** [comment]
Is this really a problem? These variable names are only used in the log file generated by OMTLMSimulator. OMEdit has been able to plot this file before.

**Comment by lochel** [comment]
It is a problem, because we cannot access those variables from the API.

**Comment by robbr48** [comment]
In this case there are a few important requirements:

- Unit information must be stored in the CSV file (since those variables are never stored internally by the application)
- OMEdit must be able to load and plot the CSV file
- Unit information must be displayed in the OMEdit plots and in the variable tree (this was the reason why we added units in the variable names to begin with)

**Comment by lochel** [comment]
It is not possible to have meta information inside a csv file, like unit information. Why not using the mat files for this?

**Comment by robbr48** [comment]
In that case we would need to add the mat file support also to OMTLMSimulator. It is currently only available for OMSimulator. I guess it is the best solution, although we either need to duplicate the code or add some ifdef's to make OMTLMSimulator compilable as stand-alone.

**Comment by lochel** [comment]
Is it possible to send all variables to the master, so that OMSimulator can handle the result files?

**Comment by robbr48** [comment]
It could be possible to add an API call for retrieving all data as a vector of vectors. Is this how OMEdit will retrieve result data from OMSimulator API?

**Comment by lochel** [comment]
This issue seems to be obsolete.
